prometheus:
  createInstance: true
jaegerBackendExample:
  enabled: false
grafana:
  enabled: true
mongodb:
  createInstance: false
grafana:
  service:
    type: "LoadBalancer"
deviceRegistryExample:
  type: "mongodb"
  mongoDBBasedDeviceRegistry:
    mongodb:
      host: "mongodb"
      port: 27017
      dbName: "honodb"